version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"
    rust: "latest"

python:
  install:
    - requirements: h3ronpy/docs/requirements.txt
    - method: pip
      path: ./h3ronpy
